### PR TITLE
Add missing includes

### PR DESCRIPTION
**Pull request by RobinMalfait**

### CODE REVIEW

**Comment by janseeuw** [comment]
Tested both includes on the endpoints in Postman and they work:
- `/office_managers/169/offices?include=contacts`
- `/contacts/169/offices?include=contacts`

**Comment by RobinMalfait** [comment]
You tested the API not the SDK... 😅

**Comment by kendepelchin** [comment]
@janseeuw this is the SDK, this can't be tested with Postman

**Comment by janseeuw** [comment]
I know I tested the API and not the SDK. 

Tested the SDK explicitly, but receive a 403 Forbidden when using public_client. Works with public_client_password. Not sure if this is ok.

**Pull request merged**
